### ISSUE TITLE
The default metric unit is ignored

### ISSUE THREAD

**Issue by mmergenthaler** [akeneo/pim-community-dev#8342] opened 2018-06-18 11:49 UTC
In the Akeneo Demo (v2.2.9) for example the attribute "weight" is configured to use "Kilogram" as the default metric unit. But if you create a new product, on that attribute the metric unit "Milligram" is pre-selected.

How to reproduce:

- Log in to http://demo.akeneo.com/ with "admin:admin"
- Go to Products and create a new product, for example a camcorder with sku "55555"
- Aftrer the product is created on the attribute "weight" the metric unit "Milligram" is pre-selected and not "Kilogram"

[akeneo-pim-system-info_2018-06-18_11_38.txt](https://github.com/akeneo/pim-community-dev/files/2111102/akeneo-pim-system-info_2018-06-18_11_38.txt)

**Comment by jmleroux** [comment] 2018-06-20 19:57
Hello @mmergenthaler ,

thanks for this clearly described bug. I reproduced and we will add it on our issue tracker.

Regards,
JM

**Comment by LaureBro** [comment] 2018-07-17 12:17
Hello @mmergenthaler, 

Here's our internal ref PIM-7516. This ref will appear in the changelog once it is fixed. Note that this issue will be fixed from 2.3 version - 2.2 version is a Short Term Support version and is not supported anymore.
I hope you plan to update on our latest version, the 2.3 which is a Long Term Support version (18 months of support) :)

Kind regards, 
Laure

**Comment by LaureBro** [comment] 2018-09-06 13:02
Hello @mmergenthaler,

I will close this issue since it is fixed in the 2.3 version.

Kind regards, 
Laure

**Closed by LaureBro** 2018-09-06 13:02 UTC
Labels: bug
