### ISSUE TITLE
API: Upload file without write permission to file_storage returns successful status code

### ISSUE THREAD

**Issue by pardahlman** [akeneo/pim-community-dev#6172] opened 2017-05-15 14:36 UTC
Hello,

I've configured Akeneo PIM according to the [System Requirements documentation](https://docs.akeneo.com/1.7/developer_guide/installation/system_requirements/system_requirements.html). 

It turns out that in order to be able to upload files, Akeneo needs to have write access to `/app/file_storage`, which is not on the list of folders in the documentation (see _Files and folders access rights_). Perhaps I should create a separate ticket for that in the docs repo. However, the main issue here is that the http response code is a `200 OK`, which is a successful status code that does not match [the status codes in the documentation](https://api.akeneo.com/api-reference.html#post_media-files).

IMO, the status code should be in `500 Internal Error` or another status code that represent what happened.

Thoughts?

**Comment by ahocquard** [comment] 2017-05-19 09:15
Hello @pardahlman,

I could not reproduce this behavior, I have an error 422.
But I have a warning in the body.

I suppose it's the same problem here : you have a notice, and then, header is sent with code 200.
Could you check your body ?

I suppose that if you change your php log level, it should be a 422 or 500.

**Comment by pardahlman** [comment] 2017-05-22 07:07
Hello!
Yes, I get a warning message as well. The problem is that I'm interpreting the status code based on the documentation, and `200` is a "successful status code" and currently interpreted as success.

Not really sure what you mean re: log level. does it affect what status code that is returned?

**Comment by ahocquard** [comment] 2017-05-24 09:41
@pardahlman I mean that `display_errors` set to Off in php.ini, you should not have this problem (you will get a 422 or a 500 http code), because the warning will be deactivated.

This problem is not coming from the API, but is more global : it's an infrastructure problem.
Maybe we should check the write access on the directory at the installation or something like that.

**Comment by ahocquard** [comment] 2018-01-23 16:06
I think we check right access now when installing the PIM.
I close the issue.

**Closed by ahocquard** 2018-01-23 16:06 UTC
Labels: API, question
