### ISSUE TITLE
Question: Mass edit error caused by incomplete transchoice-translation in russian. 

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4227] opened 2016-03-27 15:42 UTC
If we select more than 4 products and our admin dashboard area is set to russian language we get error caused by incomplete transchoice translation. 

Quick fix is to create ```app/Resources/translations/messages.ru.yml``` and paste there fixing translation like that.

```yml
pim_enrich:
    mass_edit_action:
        product:
            page_subtitle: 'Массовое редактирование (1 продукт)|Массовое редактирование (%count% продуктов)|Массовое редактирование (%count% продуктов)'
``` 

The question: Is it fixed now in 1.5 or translations migrated from EnrichBundle?

**Comment by pierallard** [comment] 2016-03-27 15:53
Hi @a2xchip 

We recently changed Crowdin to manage versionning. I just hope this is not a regression with the previous Crowdin system.
When I look at Crowdin, I see there is a lot of missing translation or non validated translations. These ones are not automatically sent with our weekly script.
Here is the 1.5 EnrichBundle messages.yml in Russian: https://crowdin.com/translate/akeneo/238/en-ru
and this is your missing key: https://crowdin.com/translate/akeneo/238/en-ru#5611 (translated but not validated).

If you are interested, I can set you proofreader in Crowdin russian locale, to validate these strings. And if this is really blocker, we can run the script to have the very recent translations when you need it (last time was done this morning).
Btw you should not have an error, only a missing translation, I will investigate to find the issue.

Pierre

**Comment by nidup** [comment] 2016-03-27 15:55
For translations, we use a script to push new keys from github to Crowdin and to fetch proof read translations from Crowdin to Github via automatic pull requests. These PRs are opened for each version and we merge each week on related branches.
We can't directly fix translations file on github because the fix will be erased by upcoming translations PR.
The best way is to fix on Crowdin directly and to to run the script.
You can create an account on Crowdin and fix here https://crowdin.com/project/akeneo/ru 
Would you be interested to be proofreader for the Russian language?

**Comment by nidup** [comment] 2016-03-27 16:03
@pierallard yes, such reactivity! have a nice easter buddy! :rabbit:

**Comment by a2xchip** [comment] 2016-03-27 16:27
@nidup I already registered there in crowdin and made some translations last month. But couldn't remember about crowdin possibilities... Let me check it today.

**Comment by a2xchip** [comment] 2016-03-27 17:01
@pierallard Keep free to add me as proofreader to crowdin russian. Our implementation is bi-lingual and will use both russian and romanian. But I didn't checked for romanian yet and i'm not good romanian speaker... If there is no a lot of romanian speakers participating on crowdin i may ask our manager who is moldovian/russian speaker to register on crowdin too.

**Comment by pierallard** [comment] 2016-03-27 17:11
@a2xchip Done ! You can now validate translations.
For "mass validation", you should have access to new options in this page
https://crowdin.com/project/akeneo/ru#
In the right, the "...", you have "open in proofreading mode", it helps to validate several translations in one page.
If you want us to run manually the Crowdin script, just ask! Else, it will run at the end of the next week.

Big thank again for participating to the translation of Akeneo!

**Comment by a2xchip** [comment] 2016-03-27 20:51
@pierallard @nidup Our users informed me that these quick fix i wrote works for ```pim_enrich_mass_edit_action_choose``` page but it comes back with another subtitles translation on any of chosen mass actions ```pim_enrich_mass_edit_action_configure``` action page.

**Comment by a2xchip** [comment] 2016-03-27 21:56
@nidup @pierallard The biggest problem in all project translation is vernacular translation 'продукт/ы' for  products (i think it is because of its consonance with english products which sounds same) that may be culturally used only for grocery goods but in businesses and commercial world people use word 'товары' for products.

It is very hard to change it in all strings now. But may be we can do it in feature versions.

**Comment by pierallard** [comment] 2016-03-27 22:11
What version of the PIM do you use? It is probably a side effect of the version management of Crowdin. If you use an "old" version, there was some rollbacks for some translations (we don't find the criteria of these, but other translators denote only a few).
You can check the last "Update Crowdin" commit (from me) in your branch to display last changes.

**Comment by a2xchip** [comment] 2016-03-27 22:20
@pierallard It is 1.4.22 on server 
![image](https://cloud.githubusercontent.com/assets/6627334/14068145/be03f260-f482-11e5-99df-7fcb4cd15e41.png)

And the same on development machine 
![image](https://cloud.githubusercontent.com/assets/6627334/14068156/116a6b64-f483-11e5-942d-8523bdd40e56.png)

**Comment by pierallard** [comment] 2016-03-28 09:45
Hi @a2xchip. 
For yout contextual product translation issue, I invite you to discuss in Crowdin forums with other Russian proofreaders to find the better way to translate "products".
You can find the list of translations with "продукт" here: https://crowdin.com/translate/akeneo/all/en-ru#q=%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82

As you maintain your 1.4 with the latest minor versions, you will have the latest Crowdin translation, that's a good point for reactivity.

Pierre

**Comment by a2xchip** [comment] 2016-03-28 12:55
@pierallard Thx. Can you pull and merge updated translation now?

**Comment by pierallard** [comment] 2016-03-28 16:06
Hi
Sorry, but today I have a nightmare internet connection... To merge, we need to be sure no test fail with our continuous integration tools. I will run it tomorrow!

Pierre

**Comment by a2xchip** [comment] 2016-03-28 16:18
Thank you @pierallard

**Comment by pierallard** [comment] 2016-03-29 15:44
Hey @a2xchip 

I ran the CI to have result, but it's not finished yet. If it's urgent for you, you can take directly my branch from my own repository! Results will be avaiable tomorrow.
https://github.com/akeneo/pim-community-dev/pull/4242
I hope it's OK for you.

Pierre

**Comment by a2xchip** [comment] 2016-03-29 17:55
@pierallard Let's wait. I can't take 

@nidup @pierallard Is there any plans to move phpspecs to dedicated bundles?

**Comment by nidup** [comment] 2016-03-29 18:03
@a2xchip in fact, we're studying the extraction of several akeneo components in dedicated readonly repositories to make them easily usable outside of the PIM. To be able to run tests on these readonly repository, we would need to move phpspec in each folder (or move them only in readonly repo). No ETA for now, still in discussion :)

**Comment by pierallard** [comment] 2016-03-29 19:35
@a2xchip I just merged your translations in the latest commit of 1.4. Is it ok for you?https://github.com/akeneo/pim-community-dev/commits/1.4

**Closed** 2016-04-04 08:01 UTC
Labels: bug
