### ISSUE TITLE
CE 2.3.2 API Request for filtering products with attribute "enable" fails

### ISSUE THREAD

**Issue by realkru79** [akeneo/pim-community-dev#8605] opened 2018-08-02 12:04 UTC
Every time i use the search filter "enabled" over the API i got the error message:
`Filter on property \"enabled\" is not supported or does not support operator \"!=\"`
I am using CE 2.3.2

**Comment by Silarn** [comment] 2018-08-02 22:50
I ran into this issue as well. It's caused by the commit: API-593: correct completness filter

The `src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml` was updated to create unique validators for various query types. In the process, 'enabled' was left off of the `pim_api.checker.query_parameters_product` definition.

Simply adding it to the array in the fourth argument fixes the issue.

**Comment by Doodoune** [comment] 2019-01-08 10:35
Hi!

Effectively, this problem was caused by this commit. It's resolved since 2.3.5 by the commit https://github.com/akeneo/pim-community-dev/pull/8650/commits/94e1e50173d150d185d4180483dea5b6bc12a801. I close this issue, feel free to re-open it if you still have this issue.

Regards,

**Closed by Doodoune** 2019-01-08 10:35 UTC
