### ISSUE TITLE
Upload Button does not show in import profile

### ISSUE THREAD

**Issue by dfranek** [akeneo/pim-community-dev#5078] opened 2016-10-04 14:39 UTC
I have the same problem as explained in Issue #5034. After creating a new CSV import profile you can not directly upload a file, if you do not specify a file path. 

![Missing upload button](https://cloud.githubusercontent.com/assets/13376225/18688951/df3f0246-7f86-11e6-9bba-7794a5571074.png)

In my opinion it should not be necessary to specify a file path (this was also the behavior in 1.5).

**Comment by fabienlem** [comment] 2016-10-10 08:06
Hi @dfranek,

I reproduced this issue, thank you for reporting it !

If you feel like contributing, you could suggest a fix through a pull request on the **master** branch. 

The wanted behavior is the following : If the user don't fill the "file" field, it's still possible to save the import profile but an error message should be displayed : "This value should not be blank".

Here is a screenshot of what it looks like in 1.4 version : 
![importprofilfilefieldempty](https://cloud.githubusercontent.com/assets/19775001/19229856/f6bc8dc2-8ed0-11e6-866b-5ccb70ac2012.png)

I'll be happy to help you by reviewing and merging this PR.

If you're interested, I'll need that you read and sign our contributor agreement to merge the pull request https://www.akeneo.com/contributor-license-agreement/

Thank you !

**Comment by a2xchip** [comment] 2016-10-16 16:32
@fabienlem If there is not enough right to write in pointed directory upload button too will be silently hidden. So there are two main occurrences: 
* first user did not filled export path;

**Comment by sammarcus** [comment] 2016-12-14 20:50
Of course, the other angle of this is that the import button is hidden if no path is specified. While an informational red message is nice to have, I think that is less of an issue that it doesn't display and the bigger issue is that the import button is hidden unless a path is specified. Forgive me if this was obvious, but it seems like there are 2 different concerns here? (Displaying a warning when left blank and ALSO allowing an import to proceed when value is blank).

**Comment by LaureBro** [comment] 2017-03-13 13:13
Hello, 

A quick message to let you know that this behaviour is fixed in the upcoming 1.7 :tada:
The drag&drop zone is always displayed whether you have a file path added or not.
The file path is not mandatory anymore.

Regards, 
Laure

**Closed** 2017-03-13 13:14 UTC
Labels: bug, duplicate
