### ISSUE TITLE
Completeness does not update when changing Locale in Product Attributes View

### ISSUE THREAD

**Issue by Ghoubali** [akeneo/pim-community-dev#6856] opened 2017-09-28 12:27 UTC
https://drive.google.com/file/d/0BxMqOeCZ7IwlRTZoRWtGNmJHMlk/view

As you can see in the video attached.
The completeness does not update when changing the Locale option.
To update it, you have to re-select the Channel.

**Comment by LaureBro** [comment] 2017-10-31 15:39
Hello @Ghoubali, 

The issue is fixed on the latest version, the 2.0.5. 

Kind regards, 
Laure

**Closed** 2018-02-15 10:18 UTC
Labels: bug
