### ISSUE TITLE
Slow product import with Version 1.4.4

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3429] opened 2015-10-19 08:41 UTC
I have noticed that the product import in Akeneo 1.4.4 is about 3 times slower than with Akeneo 1.4.3. I didn't expect this from the CHANGELOG notes.

We use the default `app/console akeneo:batch:job csv_product_import` to import about 150 * 1000 products with 250 attributes. I've tested the import several times with Version 1.4.3 and 1.4.4.

**Comment by jmleroux** [comment] 2015-10-23 07:52
3 times slower between 1.4.4 and 1.4.3 ?
Are you sure it's not between 1.3 and 1.4 ?

Thanks for the feedback,
JM

**Comment by Hocdoc** [comment] 2015-10-27 08:46
Yes, it's between 1.4.4 and 1.4.3.
(We are using MySQL as database backend.)

V. 1.4.4 seems to be also more strict which values are accepted during the import (f.ex. the metric value `1.23abc` is imported in V. 1.4.3 without warning, but there is an error in V. 1.4.4), which is a good thing.

**Comment by sagikazarmark** [comment] 2015-11-18 16:46
CSV import is indeed slower for me on 1.4.9 as well: importing 24000 products took 5 hours with multiselect 40 attributes.

**Comment by nidup** [comment] 2015-12-11 03:34
FYI we're currently working on our performance guide, you can find extra info here http://docs.akeneo.com/latest/reference/performances_guide/index.html

Are you running in prod mode without xdebug enabled ? Are you encountered memory leak?

As any catalog is different it's quite hard to give a general and accurate answer, for this kind of issue we advise to profile with https://blackfire.io/

It will allow you to spot the greedy parts of the process, if you can share the graph, we'll be able to help

**Comment by Hocdoc** [comment] 2015-12-14 07:33
I've done the import in prod mode without xdebug enabled.

Thanks for the useful performance guide & profiler link. I will try the profiler if I can get some free time in the future. As we don't import products very often, the import performance isn't that important for us. We just wondered why there was such a huge import speed difference between 1.4.3 and 1.4.4.

**Comment by nidup** [comment] 2016-01-23 10:10
Hi @Hocdoc 
By auditing the application with different data set, I think encountered the issue that you described here.
I didn't encountered it on my previous tests because I measured products updates and the regression only impact product creation.
You may be interested by this work in progress pull request https://github.com/akeneo/pim-community-dev/pull/3916 
FYI, we're working on adding automatic perf tests in our continuous integration to be able to easily detect this kind of issues before to ship them.
Thank you again for the feedback, it's very valuable for us!

**Comment by nidup** [comment] 2016-02-09 17:00
Has been fixed with #3939 will be released in the upcoming 1.4.19.

**Closed by nidup** 2016-02-09 17:00 UTC
Labels: bug, performance

**Comment by phaseinducer** [comment] 2016-02-11 14:36
The patch is available ; )

**Comment by Hocdoc** [comment] 2016-02-12 09:45
Wow, this patch gives use a real performance boost.

In Akeneo 1.4.18 we needed 82 hours to import 150,000 products.
In Akeneo 1.4.19 we need just 11 hours for the same job (=7 times faster!).

Also re-calculating the completeness is now 3 times faster.

Thanks for this amazing work!

**Comment by nidup** [comment] 2016-02-12 10:08
Thank you very much for the feedback @Hocdoc !
We're still working a lot on this topic cf http://docs.akeneo.com/latest/reference/scalability_guide/index.html and http://docs.akeneo.com/latest/reference/performances_guide/index.html
