### ISSUE TITLE
1.6 Product export filter - reference data attributes

### ISSUE THREAD

**Issue by JulienDotDev** [akeneo/pim-community-dev#5207] opened 2016-11-07 16:57 UTC
**I'm reporting a Bug**

Local Akeneo 1.6.4

When using product export filter in job config, error occured when i tried to add a reference data select attribute.

I didn't found any doc where it says that reference data are not supported in product export job filter.

`INFO - Matched route "pim_ui_ajaxentity_list". 
Context: {"route_parameters":{"_controller":"pim_ui.controller.ajax_option:listAction","_format":"json","_route":"pim_ui_ajaxentity_list"},"request_uri":"http://akeneo.akeneo-dev.loc/app_dev.php/list.json?class=undefined&collectionId=1&dataLocale=fr_FR&options%5Btype%5D=code&referenceDataName=supplier"}
CRITICAL - Uncaught PHP Exception Doctrine\Common\Persistence\Mapping\MappingException: "Class 'undefined' does not exist" at /var/www/akeneo/akeneo-dev/akeneo/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php line 96 
Context: {"exception":"Object(Doctrine\\Common\\Persistence\\Mapping\\MappingException)"}`

**Comment by JulienDotDev** [comment] 2016-11-07 17:06
Looks like this PR is related to my issue : PIM-5635

**Comment by fabienlem** [comment] 2016-11-09 16:51
Hello @JulienDotDev,

The PR you mentioned will not be merged. I gather further information on your issue and I will keep you updated.

Regards,
Fabien

**Comment by fabienlem** [comment] 2016-11-14 16:06
Hi @JulienDotDev,

I'm not able to reproduce your issue. Can you try to clone the master branch and then to copy only the reference data relative's custom developments on it. Please let me know if the issue is still reproducible in this conditions.

Regards,
Fabien

**Comment by JulienDotDev** [comment] 2016-11-15 09:05
Hi @fabienlem,

with pim-community-dev 1.6.4, custom-entity-bundle 1.8.*
Dataset : PimInstallerBundle:icecat_demo_dev

I added my referencedata bundle (2 reference data : brand and supplier)
I created an attribute to create a simple select.
I added the attribute to a product and selected an option, saved it.
I go to the export product job, edit filters, i try to add my new attribute based on my reference data > nothing happens.

Regards,

**Comment by taniot** [comment] 2018-10-03 08:12
Is there any news on this issue?
I'm having the same problem in version 2.3.10

Thanks

**Comment by Doodoune** [comment] 2019-05-22 13:23
Hi!
I try to reproduce this issue on a vanilla PIM 2.3.43 and I don't reproduce this issue. Can you provide me a step by step example to reproduce it?
Regards,

**Comment by Doodoune** [comment] 2019-07-22 12:08
Hi! I close this issue. 
Feel free to reopen it with more details to reproduce the bug :)
Regards,

**Closed by Doodoune** 2019-07-22 12:08 UTC
Labels: to reproduce
