### ISSUE TITLE
the added filter has disappeared

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#9498] opened 2019-02-01 08:52 UTC
Hi,
Not sure if it is a bug but it is a bit frustrating : on the products grid, add a filter (+) .... it works great !
Go on another page (for example parameters) ... then go back to the products grid >> the added filter has disappeared (so if you add "x" filters you have to add them again !). Not user friendly

Akeneo 2.3.27

Thanks

**Comment by Doodoune** [comment] 2019-03-21 14:27
Hi @grabelle!

It's not a bug. By default, we provide these filters. But if you want other "by default" filters, you can edit your user and select in "Product grid filter" filters that you want to see "by default" in your product grid.

Ex:
![user_interface](https://user-images.githubusercontent.com/34027529/54758795-231dd200-4bed-11e9-9a17-f5570084147f.png)

With this configuration, every time I'm logged with my Admin user, I have the filter Family, Status, Sku, and EAN visible.

Regards,

**Comment by Doodoune** [comment] 2019-04-04 09:48
I close this issue. 
Feel free to reopen it if needed.
Regards,

**Closed by Doodoune** 2019-04-04 09:48 UTC
