### ISSUE TITLE
Akeneo 1.5.7 fresh. Variants group and groups doesn't displays. 

### ISSUE THREAD

**Issue by x-lex** [akeneo/pim-community-dev#4748] opened 2016-07-20 11:06 UTC
Installation is fresh, cloned from github repository.

** System information: 
[akeneo-pim-system-info_2016-07-20_10-59.txt](https://github.com/akeneo/pim-community-dev/files/373526/akeneo-pim-system-info_2016-07-20_10-59.txt)

When I tried get Variant group(or just group) by url `/app_dev.php/enrich/variant-group/` I take a view without any entity(In database they are). In console I have a 500 error for requested url `/app_dev.php/datagrid/variant-group-grid/load?localeCode=en_US&groupTypes%5B%5D=1&params%5BlocaleCode%5D=en_US&params%5BgroupTypes%5D%5B%5D=1`

Symfony debug: 
`An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT COUNT(*) FROM (SELECT p0_.id AS id0, p0_.code AS code1, (CASE WHEN p1_.label IS NULL THEN p0_.code ELSE p1_.label END) AS sclr2, (CASE WHEN p2_.label IS NULL THEN p3_.code ELSE p2_.label END) AS sclr3, p1_.label AS label4, p0_.product_template_id AS product_template_id5, p0_.type_id AS type_id6 FROM pim_catalog_group p0_ LEFT JOIN pim_catalog_group_translation p1_ ON p0_.id = p1_.foreign_key AND (p1_.locale = ?) LEFT JOIN pim_catalog_group_type p3_ ON p0_.type_id = p3_.id LEFT JOIN pim_catalog_group_type_translation p2_ ON p3_.id = p2_.foreign_key AND (p2_.locale = ?) LEFT JOIN pim_catalog_group_attribute p5_ ON p0_.id = p5_.group_id LEFT JOIN pim_catalog_attribute p4_ ON p4_.id = p5_.attribute_id INNER JOIN pim_catalog_group_type p6_ ON p0_.type_id = p6_.id AND (p6_.id IN (?)) GROUP BY p0_.id) AS e' with params ["en_US", "en_US", "1"]:

SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'symfony.p1_.label' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by") in PimDataGridBundle:Datagrid:load.json.twig at line 3.`

**Comment by aRn0D** [comment] 2016-07-20 15:08
Hi,

I can not reproduce that bug, can you tell us a little bit more? Did you import data?

Thanks.

**Comment by x-lex** [comment] 2016-07-21 10:27
Hello, I just clone master branch and run the installation. That is all. I think problem is has been because was MySql 5.7 version.

**Comment by x-lex** [comment] 2016-07-21 10:30
The same problem was with early versions of pim. You can find them in issue tab. If you need I can send you archive with my docker instance where you can reproduce this problem. I hope this information can help you. Have a nice day !

**Comment by LaureBro** [comment] 2016-07-21 13:02
Hello @x-lex, you are right, it's because you're using MySql 5.7 version.
The solution is this case is to disable only_full_group_by mode.

Best regards, 

Laure

**Comment by nidup** [comment] 2016-08-17 16:48
I close this issue, I referenced the enhancement here https://github.com/akeneo/pim-community-dev/issues/4855.

**Closed by nidup** 2016-08-17 16:48 UTC
Labels: question
