### ISSUE TITLE
Product value = 0 not saved when required in family

### ISSUE THREAD

**Issue by jcpla** [akeneo/pim-community-dev#4179] opened 2016-03-18 13:41 UTC
Hello Akeneo Team,

There is a bug on demo.akeneo.com

On this new product : http://demo.akeneo.com/enrich/product/1123?dataLocale=en_US

I tried to save the attribute "Maximum frame rate" in the group technical with the value = "0".
=> the product is saved but not the value - it is empty.

There is a workaround : 
Put the value = "1", save the product, update to "0" and save again.

You can do it for a new product, when you first save is equal to "0".

About the completeness. 
When we have a boolean required in the family and we create a new product and let the value to false, the completeness says that this attribute is not filled.
We have to set it to Yes, save the product, update to "no" and save again,
Even if it doesn't make any sense to put a boolean attribute required, the problem is here.

Best Regard
Jcpla

[Edition]
CE

[Version]
1.5.1

[Storage]
doctrine/orm

[Environment]
prod

[Install time]

[Registered bundles]
APY\JsFormValidationBundle\APYJsFormValidationBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
Nelmio\ApiDocBundle\NelmioApiDocBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\FormBundle\OroFormBundle
Oro\Bundle\NavigationBundle\OroNavigationBundle
Oro\Bundle\RequireJSBundle\OroRequireJSBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UIBundle\OroUIBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\BaseConnectorBundle\PimBaseConnectorBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\JsFormValidationBundle\PimJsFormValidationBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\TransformBundle\PimTransformBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Pim\Bundle\WebServiceBundle\PimWebServiceBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle

**Comment by nidup** [comment] 2016-03-19 08:29
Hi @jcpla 
Thank you for the detailed feedback!
We managed to reproduce it, the issue is due to a change in 1.5 impacting the use of optional attribute (attributes added directly in the product and not in its family).
We created an issue in our internal bug tracker (number PIM-5666), our team will handle it and we'll keep you posted once fixed.

**Comment by nidup** [comment] 2016-08-18 16:49
Hi @jcpla 

This :bug: has been fixed in v1.5.3 https://github.com/akeneo/pim-community-dev/blob/master/CHANGELOG-1.5.md#153-2016-05-13

Have a good day!

**Closed by nidup** 2016-08-18 16:49 UTC
Labels: criticity major, type bug
