### ISSUE TITLE
new created attribute groups are only shown after a reboot

### ISSUE THREAD

**Issue by simonkub** [akeneo/pim-community-dev#7063] opened 2017-10-24 15:32 UTC
**I'm reporting a Bug**

If you create a new attribute group (`/#/configuration/attribute-group/create`), save it and go back to the attribute group screen (`/#/configuration/attribute-group/`) the new attribute does not appear. You have to reload the page to see the created attribute group.

The same applies to deleting an attribute group, you have to reload the page for the deleted attribute to disappear.

Tested on 2.0.4 CE with Chrome/Firefox.

#### Steps to reproduce
1. Create a new attribute group (`/#/configuration/attribute-group/create`)
2. Save it 
3. Click on the `Attribute groups`-Link in the Settings-Navigation column
4. Confirm that the created attribute group is not shown
5. Reload the page for the attribute to appear

![systeminfo](https://user-images.githubusercontent.com/16416949/31952616-5b0eebfe-b8e1-11e7-8b6e-ad21ff66d135.png)

**Comment by KarenMayo** [comment] 2017-10-25 15:09
Hello @simonkub, 

Thanks for raising this issue. 

I will let you know as soon as the fix is available.

Regards,
Karen

**Comment by Doodoune** [comment] 2018-11-21 10:47
Hi!

This issue is solved in the 2.3 version. I can't reproduce the problem on http://demo.akeneo.com.
I close this issue. 
Feel free to reopen it if you still have this issue.

Regards,
Elodie

**Closed by Doodoune** 2018-11-21 10:47 UTC
