### ISSUE TITLE
In List filter forgets old filter value

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4481] opened 2016-05-19 07:59 UTC
**I'm reporting a Bug**

The In-List-filter "forgets" the previous selected list entries.

Steps to reproduce with Akeneo 1.5.3 on http://demo.akeneo.com/ :

1. Add a filter for the attribute `Brand` in the product grid
2. Add in this filter with "in list" the value `Canon` and click the "Update" button
3. Click again on the `Brand` filter. 

Now the "in list" box is empty (instead of the expected `Canon` value), which is confusing for our users.

You also cannot remove the `Canon` value without removing the whole `Brand` filter, you just can add other values to the filter.

**Comment by LaureBro** [comment] 2016-05-19 08:39
Hello Hocdoc, 

Thanks for reporting this, I've noticed the same behaviour (https://github.com/akeneo/pim-community-dev/issues/4435) and already created a bug ticket in our bug tracker system PIM-5802.
We'll keep you updated.

Thanks & Regards,

Laure

**Comment by Hocdoc** [comment] 2016-05-19 08:43
Ok thx!
(I didn't realized that issue 4435 is also about this before.)

**Comment by LaureBro** [comment] 2016-05-19 08:46
When trying to reproduce the behaviour described in the #4435 I've noticed this bug - I actually did not describe it very exhaustively ;)
_I have noticed a bug when you filter on a brand, once you have added a brand, you cannot remove it unless you remove and then add again the attribute._
Let's keep this issue open - since the other was more related to the behaviour of the "in list" filter.
Thanks!

**Comment by LaureBro** [comment] 2016-05-31 08:17
Hello @Hocdoc 

The issue on the brand filter will be fixed in the next 1.5 version.
We're planning to release the patch this week.

Best regards, 

Laure

**Comment by LaureBro** [comment] 2016-06-03 12:55
hello @Hocdoc, the 1.5.4 version is now available.
It contains the fix for this issue.
I'm closing this ticket. Thanks!

**Closed by LaureBro** 2016-06-03 12:55 UTC
Labels: bug

**Comment by Hocdoc** [comment] 2016-06-13 10:04
Thanks, this fixes our issue.
