### ISSUE TITLE
On Delete of Product(s), Submit Button is Named "PIM_DATAGRID.MASS_ACTION.DELETE.LABEL"

### ISSUE THREAD

**Issue by oritzvielli** [akeneo/pim-community-dev#7443] opened 2018-01-05 08:01 UTC
**I'm reporting a Bug**

CE Version 2.0.10, go to "Products", checkbox specific product(s) and click on "Delete". 

Next window shows delete button but it says "PIM_DATAGRID.MASS_ACTION.DELETE.LABEL"

**Comment by pierallard** [comment] 2018-01-08 14:20
It means that a translation is missing in this file.
It's an easy pick, I let anybody pick it !

https://github.com/akeneo/pim-community-dev/blob/2.0/src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml#L84

**Comment by akosglue** [comment] 2018-01-18 08:48
Hello,

In my opinion this fix should be somewhere else.
The reference to the translation should be: PIM_DATAGRID.MASS_ACTION.DELETE.CONFIRM_OK, because that translation exists already.
(in 2.1 it is already fixed anyways)
I could create a PR for this in 2.0, if it is no problem to have this in the translation file:
            confirm_ok:      OK
            label:           OK
However, changing the reference to the translation seems a cleaner fix to me. (just like in 2.1)

**Comment by Doodoune** [comment] 2018-12-27 16:05
Hi oritzvielli!

I cannot reproduce it on our last version of 2.0 (2.0.45).
Please upgrade your PIM in the last version.
I close this issue, but if you still have this issue after that, feel free to re-open it. :)

Regards,

**Closed by Doodoune** 2018-12-27 16:05 UTC
Labels: EasyPick, bug, wanna-contribute
