### ISSUE TITLE
500 error on a fresh install [on docker container]

### ISSUE THREAD

**Issue by QwertyZW** [akeneo/pim-community-dev#6222] opened 2017-05-29 17:24 UTC
**PHP version: 5.6.30**
**Mysql version: 5.6**

After installing a fresh minimal installation of akeneo from `http://download.akeneo.com/pim-community-standard-v1.7-latest.tar.gz #for minimal version` , I successfully land on the normal login page. 

However after inputting the correct credentials and clicking on 'LOG IN'
I land on a page that looks like this

```
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

and this is what the tail of the error log looks like:

```
root@ebd12080e6b1:/var/www/pim-community-standard# tail --follow /var/log/apache2/error.log 


                                                                    
  [Symfony\Component\Debug\Exception\ClassNotFoundException]        
  Attempted to load class "DOMDocument" from the global namespace.  
  Did you forget a "use" statement?                                 
                                                                    

oro:translation:dump [--debug [DEBUG]] [--] [<locale>]...


                                                                    
  [Symfony\Component\Debug\Exception\ClassNotFoundException]        
  Attempted to load class "DOMDocument" from the global namespace.  
  Did you forget a "use" statement?                                 
                                                                    

oro:translation:dump [--debug [DEBUG]] [--] [<locale>]...
```

**Comment by mickaelandrieu** [comment] 2017-05-30 12:29
Hello @QwertyZW,

are you using PHP7? If you do, you need to install additionnal `xml` extension (which is not embed with PHP) as described in the documentation for [installation using PHP7](https://docs.akeneo.com/latest/developer_guide/installation/system_requirements/system_install_debian8_php7.html#system-installation).

Notice our support of PHP7 right now is experimental and you may have some issues.

Let me know if you need help,

**Comment by LaureBro** [comment] 2017-05-30 13:28
Hi @mickaelandrieu, according to the info given, @QwertyZW is using PHP 5.6 ;)

**Comment by mickaelandrieu** [comment] 2017-05-30 13:34
@LaureBro oh yes... so weird cause the extension required is embed with PHP in 5.6, I believed. You probably don't use apache then (note we don't officially support nginx for now).

The solution is to install the related extension(xml extension is embed in php mod for apache2):

```
apt-get install libapache2-mod-php5
```

You should then see the extension enabled:

```
php -i | grep 'xml'
```

**Comment by QwertyZW** [comment] 2017-05-30 15:20
@mickaelandrieu I'm using apache 2.4.18.

the `xml` extension is installed and is enabled.

`php -i` will **not** indicate what php modules are currently loaded in your http server; it will only tell you what the commandline `php` is loading. To get the php related info from apache one way is to call phpinfo() in a script and access that via the browser.

With that said, this is copy/pasted from a phpinfo() I placed at `pim-community-standard/web`
```
dom

DOM/XML	enabled
DOM/XML API Version	20031129
libxml Version	2.9.4
HTML Support	enabled
XPath Support	enabled
XPointer Support	enabled
Schema Support	enabled
RelaxNG Support	enabled
```

So DOM is indeed enabled.

**Comment by mickaelandrieu** [comment] 2017-05-30 19:54
You're right (about extensions enabled in cli/apache) but doesn't matter here cause when installed the extension is enabled everywhere by default :)

About your docker environment, I ..  don't know. We don't support docker officially even if we have a work in progress pull request in master branch. I suggest you to take a look to @damien-carcel images cause they are used for our CI needs, they should works.

**Comment by QwertyZW** [comment] 2017-06-08 15:22
Here's my `phpinfo()` output in html.

[phpinfo.txt](https://github.com/akeneo/pim-community-dev/files/1061480/phpinfo.txt)

**Comment by mickaelandrieu** [comment] 2017-06-08 21:47
The problem is that we don't officially support docker, you may ask for help in the slack user group or take a look at @damien-carcel images as I suggested 👍

**Comment by QwertyZW** [comment] 2017-06-08 22:17
No worries, I got past the problem by making an image of the working container and simply installing akeneo without sample data on containers spun off  said image.

I don't think it's a docker related issue anyway, although it might be.

Plz feel free to close this issue

**Comment by damien-carcel** [comment] 2017-06-09 12:19
Thank you for your feedback @QwertyZW . I close the issue as you as. Don't hesitate to reopen it (or a new one) if you have any more questions.

Regards,
Damien

**Closed by damien-carcel** 2017-06-09 12:19 UTC

**Comment by QwertyZW** [comment] 2017-06-11 00:44
I don't know how I feel about closing this one before it's actually figured out though, it's currently in the way of getting an akeneo instance running.

**Comment by radhikavm** [comment] 2020-03-02 10:18
Sorry @QwertyZW I am experience similar issue, getting a 500 error using docker. However you did mention you had managed to resolved this issue, some help would be really helpful.
