### ISSUE TITLE
docker: Error response from daemon: Mounts denied: EOF.

### ISSUE THREAD

**Issue by simplenotezy** [akeneo/pim-community-dev#11398] opened 2020-01-14 12:14 UTC
**I'm reporting a Bug**
When trying to install with Docker on MacOS:

    [constantsolutions:~/Projects/pim]$ docker run -u www-data -v $(pwd):/srv/pim -w /srv/pim --rm akeneo/pim-php-dev:4.0 \
    php -d memory_limit=4G /usr/local/bin/composer create-project --prefer-dist \
    akeneo/pim-community-standard /srv/pim "4.0.*@stable"

`docker: Error response from daemon: Mounts denied: EOF.`

When trying to use composer:

      mkdir(): Permission denied

I have tried resetting permissions for composer to no avail.

**Comment by jmleroux** [comment] 2020-02-21 14:26
Hello @simplenotezy ,

I am not a Mac user and cannot directly help you but i can suggest you to have a look at the Akeneo Slack UserGroup to be in touch with a lot of our community members. There will probably be other Mac users who will be able to help you.

https://www.akeneo.com/support/

Regards

**Comment by simplenotezy** [comment] 2020-02-24 10:33
Ok thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bugsyaya** [comment] 2020-02-27 11:37
Hey @simplenotezy,

It looks like you have a problem with docker volume.

Can you check if in the docker's setting, on `Resources > File sharing`, you have the folder where you run your command line?

![image](https://user-images.githubusercontent.com/11556581/75441033-31c44b80-595d-11ea-835c-ec93064e82a2.png)

I run it on my `Users/Desktop` and I haven't reproduced your error.

If all is ok, but that you have ever the error, can you put here more information about the error message, please?

**Comment by jmleroux** [comment] 2020-03-12 12:57
I will close this issue without answer since 15 days. Feel free to reopen it if needed.

**Closed by jmleroux** 2020-03-12 12:57 UTC
Labels: question
