### ISSUE TITLE
Multi-Select Issue in product edit and import CSV

### ISSUE THREAD

**Issue by CristinaVivi** [akeneo/pim-community-dev#6435] opened 2017-07-19 09:24 UTC
**I'm reporting a Bug**

I have an issue with the multi-select attributes. 
Although they're all added to the family of the product only a few of them display in the Edit page. 
Also there is a problem with the CSV import of these attributes.
When I import attributes such as text, simple select, image, etc, they are updated for the products, 
but the multi-select values don't update for the products. 
There are no warnings and the profile import is completed. 
 
[akeneo-pim-system-info_2017-07-19_12-15.txt](https://github.com/akeneo/pim-community-dev/files/1158620/akeneo-pim-system-info_2017-07-19_12-15.txt)

**Comment by LaureBro** [comment] 2017-07-24 16:13
Hello @CristinaVivi, 

I cannot reproduce the same issue on my installation CE 1.7.6. I've added 20 new multi-select attributes, added them to a family via the UI and through import the 2nd time, and they are all well displayed in the product edit form.
I have also updated multi-select attributes through imports, add/remove/edit values, and it works fine.

> Although they're all added to the family of the product only a few of them display in the Edit page.
Are these attributes available for all locales? If an attribute is locale specific it will only appear for the selected locales. 

> When I import attributes such as text, simple select, image, etc, they are updated for the products,
but the multi-select values don't update for the products.
Do you upload the multiselect option code and not their values?

thanks, 
Laure

**Comment by Doodoune** [comment] 2019-01-16 14:21
I close this issue,
if you still have an error, feel free to reopen it.

Regards,

**Closed by Doodoune** 2019-01-16 14:21 UTC
Labels: to reproduce
