### ISSUE TITLE
Error 500 on some product and unable to launch export job

### ISSUE THREAD

**Issue by fatoldsun00** [akeneo/pim-community-dev#12185] opened 2020-06-01 11:38 UTC
:bug: **I'm reporting a Bug** :bug:
I guess ...

Hi,

We encounter a problem with some product because we have changed attribute. Overviewing  or delete product it'sno possible (error 500). I had try to reset elasticsearch and reindex product but i get this error msg

`In Client.php line 300:

  {"type":"mapper_parsing_exception","reason":"failed to parse field [values.Quantite-decimal.<all_channels>.<all_locales>] of type [double] in document w
  ith id 'product_1'. Preview of field's value: 'Array'","caused_by":{"type":"number_format_exception","reason":"For input string: \"Array\""}}`

Also, is not possible to execute export job, we get this error

`Launching job execution "176".
Command line: "'/usr/bin/php7.3' '/var/www/pim/bin/console' 'akeneo:batch:job' 'ExportExopera' '176' '--env=prod' '--email=dev@edisac.com'"
13:35:59 ERROR     [console] Error thrown while running command "akeneo:batch:job ExportExopera 176 --env=prod --email='dev@edisac.com'". Message: "sort() expects parameter 1 to be array, string given" ["exception" => TypeError { …},"command" => "akeneo:batch:job ExportExopera 176 --env=prod --email='dev@edisac.com'","message" => "sort() expects parameter 1 to be array, string given"]

In OptionsValueFactory.php line 22:

  sort() expects parameter 1 to be array, string given`

There some command for cleanup this mess ?

Thank a lot

**Comment by Doodoune** [comment] 2020-06-01 12:15
Hi @fatoldsun00,

It happened when you delete attributes and recreate them with the same code but different attribute type or scopable/localizable option.
When you delete an attribute, values for this attribute aren't deleted from your product/product models for versioning issue. If you recreate it with the same code, it will generate this kind of error message.
We don't allow to edit attributes to avoid this kind of issue.

If you really need to delete and recreate attributes and keep the same code for the attribute, please follow this process to clear correctly the value of your deleted attribute from your product/product models.

* Delete your attribute
* Execute the command `bin/console pim:product:clean-removed-attributes` - this command will delete all product value linked to deleted attributes
* Recreate your attribute and edit your products without errors

Don't forget to export your values for this attribute if you want to reimport them (according to the new type of the attribute) before executing this process, because the 2nd step deletes the values of this attribute from your product/product models.

Hope it will help you,

Best regards,
Elodie

**Comment by fatoldsun00** [comment] 2020-06-01 12:23
Hi Elodie, 

Thanks for your quickly response.
Yeah, we have guessed the issue and try clean-removed-attribute but after delete and recreate attribute (with same code).

on bin/console pim:product:clean-removed-attributes we encounter same problem that on export product job : 

` 900/1032 [========================>---]  87%14:20:48 ERROR     [console] Error thrown while running command "pim:product:clean-removed-attributes". Message: "sort() expects parameter 1 to be array, string given" ["exception" => TypeError { …},"command" => "pim:product:clean-removed-attributes","message" => "sort() expects parameter 1 to be array, string given"]

In OptionsValueFactory.php line 22:

  sort() expects parameter 1 to be array, string given
`

 but now, there are a way to fix them ?

Thanks

**Comment by Doodoune** [comment] 2020-06-01 12:27
Could you send me your exact PIM version?
Have you tried to reproduce on the last available patch for your version?

**Comment by fatoldsun00** [comment] 2020-06-01 12:33
the composer.json file contain this line
"require": {
        "akeneo/pim-community-dev": "^4.0.0"
}

and php bin/console pim:versioning:refresh
give me this Versioning is already up to date.

**Comment by Doodoune** [comment] 2020-06-01 12:38
You could found your exact PIM version in the footer of your dashboard:
Ex - in demo.akeneo.com
![screenshot_6](https://user-images.githubusercontent.com/34027529/83409782-6856aa00-a415-11ea-87eb-3844790c0ed3.png)

**Comment by fatoldsun00** [comment] 2020-06-01 12:40
Sorry ... 

Version:CE 4.0.8 Hare Tonic

**Comment by Doodoune** [comment] 2020-06-01 12:49
Executing the command if you don't delete the attribute will not work.

Please, re-delete the attribute, execute the command and then recreate your attribute. It will normally solve your issue. 

Best regards,
Elodie

**Comment by Doodoune** [comment] 2020-06-01 12:51
You could also upgrade your PIM to the latest patch version. 
We fix a lot of bug since the 4.0.8. 
You could find the changelog here:
https://github.com/akeneo/pim-community-dev/blob/4.0/CHANGELOG-4.0.md

**Comment by fatoldsun00** [comment] 2020-06-01 12:52
Thanks a lot, let's try this !

**Comment by fatoldsun00** [comment] 2020-06-01 12:54
How we can update to a minor version ?

**Comment by Doodoune** [comment] 2020-06-01 13:05
I think it's a misunderstanding, sorry if it's the case. 

To solve your issue you really need to remove the attribute, execute the command and then recreate it.

Upgrade your PIM is an advice, it will not fix this issue but will help you to solve other issues that we already fixed. Your issue can't be fixed easily, that's why I give you this process :) 

Documentation to apply a patch to your PIM:
https://docs.akeneo.com/4.0/migrate_pim/apply_patch/apply_patch_ce.html

**Comment by fatoldsun00** [comment] 2020-06-01 13:08
Ok, everinthing it s clear, we try to fix the probblem and after we apply the patch.

I will be back after for the onclusion, maybe it can help other.

Thanks

**Comment by fatoldsun00** [comment] 2020-06-02 10:21
Alright, delete attributes, delete product, inject attribute works fine

thanks

**Comment by Doodoune** [comment] 2020-06-02 11:48
Glad that it helped you.

I closed this issue. Feel free to reopen it if needed.

Best regards,

**Closed by Doodoune** 2020-06-02 11:48 UTC
