### ISSUE TITLE
[BUG]Product page empties after clicking on the title of display all attributes popin

### ISSUE THREAD

**Issue by oliverde8** [akeneo/pim-community-dev#8250] opened 2018-06-04 12:08 UTC
**I'm reporting a Bug**

1) Open a product page : 
![image](https://user-images.githubusercontent.com/3658513/40916559-7383c352-6800-11e8-8d94-c82d45de89e5.png)

2) Click on `Display all attributes`

3) In the small "popin" click on the title "Display"
![image](https://user-images.githubusercontent.com/3658513/40916599-9cd63b5e-6800-11e8-876d-c287ae0e96b3.png)

4) Everything disappears 
![image](https://user-images.githubusercontent.com/3658513/40916623-b2f5be0a-6800-11e8-8a86-9deebcc8d877.png)

Reproduced on Version:2.2.7 on the Demo website and on 2.0.25
Using Chromium

**Comment by LaureBro** [comment] 2018-06-04 12:33
Hello @oliverde8, 

Thanks for raising this issue! The good news is that this bug will be fixed in the next 2.0 version (2.0.26) :) and will soon be fixed in the 2.2 version too.

Kind regards, 
Laure

**Comment by LaureBro** [comment] 2018-06-04 12:35
As a complement, this issue is a duplicate of https://github.com/akeneo/pim-community-dev/issues/6852, follow this issue to be informed when the fix is available.
Thank you.

**Closed by LaureBro** 2018-06-04 12:35 UTC
Labels: bug, duplicate
