### ISSUE TITLE
Metric attribute create/edit - all units are not shown

### ISSUE THREAD

**Issue by wakqasahmed** [akeneo/pim-community-dev#5688] opened 2017-02-13 17:18 UTC
**I'm reporting a Bug**

Creating/Modifying an attribute of metric type doesn't show all units in case of 'Duration' metric family.

Steps to reproduce:

1) Create new metric type attribute
2) Select `Duration` from `Metric family` dropdown and you won't see Week Month and Year in the `Default metric unit` dropdown (which is there at the following measure file https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml)

<img width="1279" alt="screen shot 2017-02-13 at 9 14 41 pm" src="https://cloud.githubusercontent.com/assets/4486133/22894274/d311f5be-f231-11e6-9715-62a38690b05f.png">

Secondly, minor typo error is there in 'Electric charge' options.

<img width="1276" alt="screen shot 2017-02-13 at 9 20 59 pm" src="https://cloud.githubusercontent.com/assets/4486133/22894437/67db6612-f232-11e6-85d0-4fbf3d12bbee.png">

**Comment by willy-ahva** [comment] 2017-02-20 14:01
Hi @wakqasahmed !

I well reproduced the bug. It seems that those metric are not available in the interface https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/MeasureBundle/Family/DurationFamilyInterface.php. That's why you can find them in the dropdown.

A fix is welcome if you have time to contribute and don't hesitate if you need help :)
Thank you !

**Comment by wakqasahmed** [comment] 2017-02-21 17:52
Thanks. I added those in my extended `measure.yml` and they are working fine.

What is the use of those interfaces in `Family` folder, i could not find any classes that is implementing them?

**Comment by BatsaxIV** [comment] 2017-04-23 06:08
Hi, 

This seems to be ok in the 1.7.x version.
https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/MeasureBundle/Family/DurationFamilyInterface.php contains the missing metrics since October 2016.
It's working on demo.akeneo.com.

I can't reproduce the typo either.

This issue can probably be closed @wakqasahmed ?

**Comment by mickaelandrieu** [comment] 2017-05-17 16:02
@wakqasahmed as @BatsaxIV and @willy-ahva stated, this is now fixed in `1.7.x` branch.

Thank you for your report!

**Closed by mickaelandrieu** 2017-05-17 16:02 UTC
Labels: bug, EasyPick, wanna-contribute
