### ISSUE TITLE
CompletenessWidget is too slow

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3771] opened 2015-12-17 08:36 UTC
In the dashboard, the widget on the left side "Completeness Over Channels and Locales" (`CompletenessWidget`)  doesn't scale well. Calculating the completeness statistics takes so many resources that it kills our system:
- Akeneo 1.4.13 with MySQL
- 160,000 products with 350 attributes (yes, maybe we should use Mongo in the future)
- nearly all products are complete and enabled
- all products are in one category

MySQL has to create a temporary file with 10 GB and has to work about 15 minutes to do the query for this widget which is too much for our server and users:

``` sql
SELECT ch.label, lo.code as locale, COUNT(DISTINCT co.product_id) as total FROM pim_catalog_channel ch
    JOIN pim_catalog_category ca ON ca.root = ch.category_id
    JOIN pim_catalog_category_product cp ON cp.category_id = ca.id
    JOIN pim_catalog_product p ON p.id = cp.product_id
    JOIN pim_catalog_channel_locale cl ON cl.channel_id = ch.id
    JOIN pim_catalog_locale lo ON lo.id = cl.locale_id
    LEFT JOIN pim_catalog_completeness co
        ON co.locale_id = lo.id AND co.channel_id = ch.id AND co.product_id = p.id AND co.ratio = 100
    WHERE p.is_enabled = 1
    GROUP BY ch.id, lo.id, ch.label, lo.code
```

After deactivating the widget (`widgets.yml`), everything works fine again.

**Comment by nidup** [comment] 2016-01-20 15:24
Thank you very much for the feedback.
I reproduced it, I add it in our scalability improvements

**Comment by simoncarre** [comment] 2017-05-02 09:25
I have the same issue. I've added an index to the `is_enabled` column on ` pim_catalog_product` table, but the issue seems to come from `DISTINCT`. Do you have a solution for this problem? Or it's better to disable this widget to avoid performance issues or MySQL blocking?

**Comment by nidup** [comment] 2017-05-10 06:16
Hi @simoncarre

Thank you for reporting this issue, how many products and product values, enabled channels and locales do you have in DB?

**Comment by simoncarre** [comment] 2017-05-10 09:09
Hi @nidup 

- 35500 products
- 75 products values
- 3 enabled channels
- 1 locale

It's preproduction env not really powerful but completness widget loading create locks on database.

Thank you for your help!

**Comment by LaureBro** [comment] 2017-05-30 08:25
hello @simoncarre @Hocdoc , 
this PR #6204 should improve the PIM performance for ORM. This fix will be available in the upcoming 1.7 version (it's already available for the 1.6).

Kind regards, 
Laure

**Comment by Hocdoc** [comment] 2017-06-07 10:25
Thanks for your effort :-) !
(We still deactivate the widget as it still slow down our database and isn't used anyway by our users)

**Comment by ahocquard** [comment] 2017-06-07 10:37
@Hocdoc I'm interesting to know the time it takes with the new optimised query and why it's so slow for you. Actually it should be a lot faster.

**Comment by Hocdoc** [comment] 2017-06-07 11:43
I've just tested it once again: After 15 minutes waiting for `widget/completeness` I got an error back: 

    Uncaught PHP Exception Doctrine\DBAL\DBALException: "An exception occurred while executing '    
    SELECT t.label, lo.code as locale, COUNT(DISTINCT co.product_id) as total FROM pim_catalog_channel ch     JOIN pim_catalog_channel_translation t ON t.foreign_key = ch.id     JOIN pim_catalog_category ca ON ca.root = ch.category_id     JOIN pim_catalog_category_product cp ON cp.category_id = ca.id     JOIN pim_catalog_product p ON p.id = cp.product_id     JOIN pim_catalog_channel_locale cl ON cl.channel_id = ch.id     JOIN pim_catalog_locale lo ON lo.id = cl.locale_id     LEFT JOIN pim_catalog_completeness co         ON co.locale_id = lo.id AND co.channel_id = ch.id AND co.product_id = p.id AND co.ratio = 100     WHERE p.is_enabled = 1     AND t.locale = 'de_DE'     GROUP BY ch.id, lo.id, t.label, lo.code':  SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYBa0U0g' (Errcode: 28 - No space left on device)" at / ***/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 91 {"exception":"[object] (Doctrine\\DBAL\\DBALException(code: 0): An exception occurred while executing '    SELECT t.label, lo.code as locale, COUNT(DISTINCT co.product_id) as total FROM pim_catalog_channel ch\n    JOIN pim_catalog_channel_translation t ON t.foreign_key = ch.id\n    JOIN pim_catalog_category ca ON ca.root = ch.category_id\n    JOIN pim_catalog_category_product cp ON cp.category_id = ca.id\n    JOIN pim_catalog_product p ON p.id = cp.product_id\n    JOIN pim_catalog_channel_locale cl ON cl.channel_id = ch.id\n    JOIN pim_catalog_locale lo ON lo.id = cl.locale_id\n    LEFT JOIN pim_catalog_completeness co\n        ON co.locale_id = lo.id AND co.channel_id = ch.id AND co.product_id = p.id AND co.ratio = 100\n    WHERE p.is_enabled = 1\n    AND t.locale = 'de_DE'\n    GROUP BY ch.id, lo.id, t.label, lo.code':\n\nSQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYBa0U0g' (Errcode: 28 - No space left on device) at***/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:91, PDOException(code: HY000): SQLSTATE[HY000]: General error: 3 Error writing file '/tmp/MYBa0U0g' (Errcode: 28 - No space left on device) at ***/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:165)"} []

There was more than 22GB space left on the hard disc before the request.
I guess, we still have too many products&attributes for this widget; but we don't need it anymore.

**Comment by ahocquard** [comment] 2017-06-07 12:57
@Hocdoc this is the slow request, not the optimised one. Have you updated your pim ? In which version are you ? I think that the performance should be pretty good with your volumetry.

**Comment by Hocdoc** [comment] 2017-06-12 08:55
I was using v1.7.5. I think I may have to wait for the next release of v1.7.6, then I'll test it again.

**Comment by tamarasaurus** [comment] 2018-02-14 16:21
Hi @Hocdoc - is this still an issue for you on the 1.7.6? 

Regards,
Tamara

**Comment by Doodoune** [comment] 2018-11-06 13:43
Hi,

Has we have no information from your side since 6 month, I closing this issue.

Feel free to re-open it if it's still an issue for you.

Regards,
Elodie

**Closed by Doodoune** 2018-11-06 13:43 UTC
Labels: Waiting for feedback, scalability
