### ISSUE TITLE
Cannot remove Number field value

### ISSUE THREAD

**Issue by s0ps** [akeneo/pim-community-dev#4357] opened 2016-04-22 12:06 UTC
I cannot remove Number type field value from product. When I insert it, the value is saved correctly but if I try to remove it the flash message shows that product is successfully saved but old field value reappears.

[Edition]
CE

[Version]
1.5.1

[Storage]
doctrine/mongodb-odm

[Environment]
prod

[Install time]
2016-04-22T14:36:24+03:00

[Registered bundles]
APY\JsFormValidationBundle\APYJsFormValidationBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
Akeneo\Bundle\BufferBundle\AkeneoBufferBundle
Akeneo\Bundle\ClassificationBundle\AkeneoClassificationBundle
Akeneo\Bundle\FileStorageBundle\AkeneoFileStorageBundle
Akeneo\Bundle\MeasureBundle\AkeneoMeasureBundle
Akeneo\Bundle\StorageUtilsBundle\AkeneoStorageUtilsBundle
Doctrine\Bundle\DoctrineBundle\DoctrineBundle
Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle
Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle
Doctrine\Bundle\MongoDBBundle\DoctrineMongoDBBundle
Escape\WSSEAuthenticationBundle\EscapeWSSEAuthenticationBundle
FOS\JsRoutingBundle\FOSJsRoutingBundle
FOS\RestBundle\FOSRestBundle
JMS\SerializerBundle\JMSSerializerBundle
Knp\Bundle\MenuBundle\KnpMenuBundle
Liip\ImagineBundle\LiipImagineBundle
Nelmio\ApiDocBundle\NelmioApiDocBundle
Oneup\FlysystemBundle\OneupFlysystemBundle
Oro\Bundle\AsseticBundle\OroAsseticBundle
Oro\Bundle\ConfigBundle\OroConfigBundle
Oro\Bundle\DataGridBundle\OroDataGridBundle
Oro\Bundle\FilterBundle\OroFilterBundle
Oro\Bundle\FormBundle\OroFormBundle
Oro\Bundle\NavigationBundle\OroNavigationBundle
Oro\Bundle\RequireJSBundle\OroRequireJSBundle
Oro\Bundle\SecurityBundle\OroSecurityBundle
Oro\Bundle\TranslationBundle\OroTranslationBundle
Oro\Bundle\UIBundle\OroUIBundle
Oro\Bundle\UserBundle\OroUserBundle
Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle
Pim\Bundle\BaseConnectorBundle\PimBaseConnectorBundle
Pim\Bundle\CatalogBundle\PimCatalogBundle
Pim\Bundle\CommentBundle\PimCommentBundle
Pim\Bundle\ConnectorBundle\PimConnectorBundle
Pim\Bundle\DashboardBundle\PimDashboardBundle
Pim\Bundle\DataGridBundle\PimDataGridBundle
Pim\Bundle\EnrichBundle\PimEnrichBundle
Pim\Bundle\FilterBundle\PimFilterBundle
Pim\Bundle\ImportExportBundle\PimImportExportBundle
Pim\Bundle\InstallerBundle\PimInstallerBundle
Pim\Bundle\JsFormValidationBundle\PimJsFormValidationBundle
Pim\Bundle\LocalizationBundle\PimLocalizationBundle
Pim\Bundle\NavigationBundle\PimNavigationBundle
Pim\Bundle\NotificationBundle\PimNotificationBundle
Pim\Bundle\PdfGeneratorBundle\PimPdfGeneratorBundle
Pim\Bundle\ReferenceDataBundle\PimReferenceDataBundle
Pim\Bundle\TransformBundle\PimTransformBundle
Pim\Bundle\UIBundle\PimUIBundle
Pim\Bundle\UserBundle\PimUserBundle
Pim\Bundle\VersioningBundle\PimVersioningBundle
Pim\Bundle\WebServiceBundle\PimWebServiceBundle
Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle
Symfony\Bundle\AsseticBundle\AsseticBundle
Symfony\Bundle\FrameworkBundle\FrameworkBundle
Symfony\Bundle\MonologBundle\MonologBundle
Symfony\Bundle\SecurityBundle\SecurityBundle
Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle
Symfony\Bundle\TwigBundle\TwigBundle

**Comment by LaureBro** [comment] 2016-04-22 12:24
Hello, 

I cannot reproduce this issue on our reference environments nor on demo.akeneo.com.
Can you try to reproduce it on http://demo.akeneo.com/?

Thanks a lot, 

Laure

**Comment by s0ps** [comment] 2016-04-22 12:48
I cannot reproduce it in demo.akeneo.com
Very strange, I also tried with fresh installation of akeneo and the problem still exists. 
Any suggestions?

**Comment by LaureBro** [comment] 2016-04-22 14:52
Can you give me the exact steps you are taking?
- create an Number type attribute
- Add it to a family (or add it in the product edit form directly)
etc..
Can you check in your browser console if you have any JS error?

Thanks a lot, 

Laure

**Comment by jmleroux** [comment] 2016-04-22 18:32
@LaureBro , demo.akeneo.com is ORM based.
So maybe the problem is linked to Mongo

**Comment by s0ps** [comment] 2016-04-25 06:52
@LaureBro same problem exists with attributes that are added to family and attributes that are added on product edit form. No js errors in console.
@jmleroux Yes, the problem appears only with Mongo, ORM version works.

**Comment by LaureBro** [comment] 2016-04-28 16:06
Hello 
@jmleroux indeed! thanks!
@s0ps you're right, I've tested and I experiment the same issue on MongoDB on our 1.5.2 version. 

If you feel like making a PR to fix it you're more than welcome, we can assist you in doing this if needed :)

Best regards, 

Laure

**Comment by nidup** [comment] 2016-08-18 17:45
Hi @s0ps 

I can't reproduce the :bug: on v1.5.7, I'm pretty sure it has been fixed in v1.5.3 with this pull request which contains fixes for really close issues https://github.com/akeneo/pim-community-dev/pull/4410

Don't hesitate to re-open the issue if you're still encountering the bug once the last patch applied.

Have a good day!

**Closed by nidup** 2016-08-18 17:45 UTC
Labels: type bug
