### ISSUE TITLE
[1.6.9] Product import - Association import does not map family, categories or groups

### ISSUE THREAD

**Issue by mathewrapid** [akeneo/pim-community-dev#5549] opened 2017-01-20 11:15 UTC
**I'm reporting a Bug**

When importing data through the `csv_product_import` job, the association import ignores the `family`, `categories` and `groups` mappings. These are mappings that work for the product import part as the `@pim_connector.reader.file.csv_product` service does provide these values in it's `getArrayConverterOptions` method https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/Reader/File/Csv/ProductReader.php#L70

Service `@pim_connector.reader.file.csv_association` does not provide these mapping details https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/Reader/File/Csv/ProductAssociationReader.php#L24

**Comment by pierallard** [comment] 2017-01-24 10:12
Hi @mathewrapid 

The "association" step does not use any "family", "categories" or "groups" mapping because it's not its role.
In you look at the definition of the complete "Product Import" job, you will see that a Product Import is always preceded by a step `pim_connector.step.csv_product.import`.
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml#L123
That's the role of csv_product.import to map "family", "categories" and "groups" and update it.

If I misunderstand your bug, do not hesitate to add more details and examples.

**Comment by mathewrapid** [comment] 2017-01-24 10:41
Hi @pierallard ,

How to reproduce:
Have an import csv where one of these are not labelled in the csv as `family`, `categories` or `groups`. Have e.g. the `groups` column labelled in the csv as `Groupes`. The product import will let you define the mapping for these fields -> `Groupes` -> `groups`. When the job passes the process to the "association" import step, the _ProductAssociationReader_ uses the _ProductAssociation_ array converter to convert the csv-row.

As we can see in https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php#L71 that is uses the given product converter https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml#L168

Here comes the interesting part. When the "Product import" reader gets to it's array converter, it has the above mentioned mappings from https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/Reader/File/Csv/ProductReader.php#L70 given to it's convert in the `$options` argument https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php#L171. The same converter is called later by the `ProductAssociation`converter (https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php#L71) but here it lacks the mappings -> resulting in an `StructureArrayConversionException` in https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php#L353


Summa summarum,
> The "association" step does not use any "family", "categories" or "groups" mapping because it's not its role.

It is its role by proxy as it uses internally the `Product` array converter, which has _said_ role.


ps. The `Product`converter dependency is against a class, not an interface in https://github.com/akeneo/pim-community-dev/blob/v1.6.9/src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php#L28 making overriding it more complex.

**Comment by pierallard** [comment] 2017-02-07 15:19
Hi @mathewrapid !
Thanks for improving your message and sorry for the delay. I completely understand the bug now, and reproduce it :-(
I added a ticket in the internal Akeneo Board (SDS-976), but can not assure you it will be treated soon.
Feel free to make a pull request to fix it, Akeneo developers will help you for any question you will have!

Thanks again for bug report

**Comment by mathewrapid** [comment] 2017-03-22 10:31
Hi @pierallard !

To be honest, I don't know what would be the _best_ solution for this?

- Add said mappings to the Associoation import step?
- Don't use the `Product` ArrayConverter?

**Comment by mickaelandrieu** [comment] 2017-05-18 09:26
Hello @mathewrapid,

sorry for the delay. I can see the issue [is fixed](https://github.com/akeneo/pim-community-dev/pull/5926) in `1.7.x` but not in `1.6.x`. If you want to contribute to backport this contribution into `1.6.x` this will be very welcome :)

Have a nice day

**Comment by LaureBro** [comment] 2017-05-30 08:55
Hello @mathewrapid,

What you can do if you still have the issue is to backport the fix in your project (and maybe adapt it a bit) or upgrade on 1.7 version.
We do not plan yet to report this fix in lower versions.

Kind regards, 
Laure

**Comment by mathewrapid** [comment] 2017-05-30 09:18
Hi @LaureBro,

I'll take a look into this when I'm back working with the 1.6 project :)

**Comment by damien-carcel** [comment] 2018-04-03 15:10
Hello.

I am closing this issue as 1.6 is not supported anymore.

Feel free to reopen it if you have anymore questions.

Kind regards,
Damien

**Closed by damien-carcel** 2018-04-03 15:10 UTC
Labels: bug, wanna-contribute
