### ISSUE TITLE
[1.5.9 + 1.5.10] Multi selects doesn't work anymore

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#5111] opened 2016-10-14 09:22 UTC
**I'm reporting a Bug**

Since v1.5.9 Multiselect attributes doesn't work as expected anymore.
I've already written PR #5074 which fix the issue, but this wasn't merge in v1.5.10, as far as I can see.
(The CI fails for my PR with out-of-memory errors which should not be related with the PR.)

**Comment by fabienlem** [comment] 2016-10-14 10:01
Hello @Hocdoc 

Thank you a lot for your contribution. Unfortunately, I'm not able reproduce this behavior on our environments.

What about your multi-select attribute? Is it localizable and/or scopable?
If you create a new multi-select attribute on your 1.5.10 instance of the PIM, do you have the same issue?

Regards

**Comment by Hocdoc** [comment] 2016-10-14 10:11
The multi select attribute only displays a few options, depending on how many languages there were defined. This is also a problem for non-localizable and non-scopable multi-select-attributes.

Example: 20 defined PIM-languages with a multi-select: Only one attribute options will get displayed (because of the `limit: 20`), even if there are much more options. 

With Akeneo 1.5.8 or Akeneo >1.6 this works as expected.

**Comment by a2xchip** [comment] 2016-10-17 08:25
@Hocdoc any updates on this?

**Comment by fabienlem** [comment] 2016-10-17 15:05
Hello @Hocdoc @a2xchip,

Thank you for your feedback!

I have similar feedback from other PIM users. I'm investigating on this issue. I'll keep you updated as soon as possible.

Kind regards

**Comment by fabienlem** [comment] 2016-10-19 12:39
Hello @Hocdoc, @a2xchip,

We made a fix for this issue. It will be available on the next 1.5.11 version and on the 1.6.4 version which will be released very soon.

We fixed this on our side because there were impacts regarding scalability, harmonization between simple and multi select attributes, and we also wrote behats tests to avoid regressions.

Hocdoc, your fix was good, but we had to keep the pagination for scalability reason.

`options: {
limit: 20,
locale: UserContext.get('catalogLocale'),
page: page
}`

Thank you a lot for your valuable help. I'm closing your PR.

Regards

**Comment by fabienlem** [comment] 2016-10-21 13:45
I'm closing this issue, feel free to reopen it if you want further information.

**Closed by fabienlem** 2016-10-21 13:45 UTC
Labels: bug

**Comment by a2xchip** [comment] 2016-10-21 15:24
@fabienlem Thx! :+1:

**Comment by a2xchip** [comment] 2016-10-21 15:25
@fabienlem Please reference the pull request of Akeneo team
