### ISSUE TITLE
JS Error, view extension being loaded in product edit page.

### ISSUE THREAD

**Issue by nei** [akeneo/pim-community-dev#6280] opened 2017-06-12 11:31 UTC
**I'm reporting a Bug**

I am getting the error on the product edit page PIM 1.7 EE.

It is trying to execute js from the product grid on the product edit form, it seems it is trying to load the create view button there but the zone is not yet available. Debugging the js I can see the area buttons is being created normally for the next interactions.

So, I am assuming it is loading js in the wrong place.

Error: Zone "buttons" does not exist at child.getZone (https://project.com/bundles/pimenrich/js/product/form.js:231:27) at child.renderExtension

It seems there are more people experiencing this issue described https://github.com/akeneo/pim-community-dev/issues/6066

**Comment by LaureBro** [comment] 2017-06-12 12:08
Hi @nei, 
What is your exact PIM version? Are you on the latest 1.7 version (the 1.7.5)? 
Thanks!

**Comment by nei** [comment] 2017-06-12 12:15
It is 1.7.1 but I checked the history of the file it seems there is no recent changes on it.

**Comment by DavidFeller** [comment] 2017-06-12 12:18
Hi @LaureBro,

I first discovered this issue in 1.7.4, but updated to 1.7.5 recently. It still occurs, but there seems to be a simple workaround: If you mark the image-attribute as required in a family the upload form field shows up and works as expected.

**Comment by momoss** [comment] 2017-06-13 09:49
Hi @nei and @DavidFeller,

We tried to reproduce this behavior, but unfortunately, we could not. Can you provide us with more information about how to reproduce it? 

Can you try to rebuild all your assets with the following commands line:

`cd /path/to/your/pim/
rm -rf ./web/bundles/* ./web/css/* ./web/js/*
php app/console pim:install:assets --env=prod
php app/console assets:install --symlink web
php app/console cache:clear --env=prod`

Thanks!

**Comment by DavidFeller** [comment] 2017-06-13 10:17
Hi @momoss,

I'll try to rebuild all assets and/or reproduce it with a "fresh" installation. Please let me get back to you tomorrow.

Thanks! 
David

**Comment by DavidFeller** [comment] 2017-06-13 14:28
Hi @momoss,

it seems like removing and reinstalling the assets did the trick. I cleared the cache several times before, but I never completely deleted all assets. Now I can't reproduce anymore either (v1.7.5 CE). :-)

Thanks for your help!

**Comment by momoss** [comment] 2017-06-15 15:23
Hi @nei,

Did you find answers to your questions?
If so, can we close this issue?

Regards

**Comment by LaureBro** [comment] 2017-06-29 08:43
I'm closing this issue, the fix is indeed to reinstall assets, this command can be used:
```
rm -rf ./web/bundles/* ./web/css/* ./web/js/* ./app/cache/
php app/console pim:installer:assets --env=prod
```
Thanks!

**Closed by LaureBro** 2017-06-29 08:43 UTC
