### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by znob** [akeneo/pim-community-dev#10389] opened 2019-07-17 22:00 UTC
**I'm reporting a Bug**

Please update to the last available patch for the version.

For version >= 1.4, please go to "System > system info", download the text report and attach it to the issue.
Hey, I'm just getting started with Akenio
When I export to CSV or Excel, the spreadsheets come out blank.
Anyone ever have that issue?

**Comment by wpperform** [comment] 2019-07-17 22:56
Oh, this is likely not a bug.  Products only export if they are assigned to a category in the category tree.  Be sure they're assigned.  

Further, products only export if they match your export profile settings, such as for completeness.  If you choose to export only complete products, and the products you expect to export are incomplete, your export files will be blank.  

It might be a good feature suggestion to alert you that no products matched your export profile settings.

**Closed** 2019-07-18 12:09 UTC
