### ISSUE TITLE
"Is empty" filter is not working correct

### ISSUE THREAD

**Issue by McSurf84** [akeneo/pim-community-dev#7442] opened 2018-01-04 16:11 UTC
When I create a new number attribute and I want to filter in the product overview for this attribute and the "Is empty" option is selected no products will be found. 
Tried to reproduce it in the demo system. http://demo.akeneo.com/#/enrich/product/ even shows "Error! Incorrect server response." after selecting the filter.
Querying on CLI with "php bin/console pim:product:query" is working properly.

**Comment by omolto** [comment] 2018-02-09 10:30
Hi,

We also experience strange behaviour with the "Is empty" filter on the web interface.

If a product is created via API with a pim_catalog_simpleselect or pim_catalog_multiselect field as null it doesn't appear on web interface filter queries as "Is empty". Althought, if you do the same query via API it appears correctly.

The "Is empty" filter must work equal on all interfaces, web, cli and api, otherwise it is a degradation of functionality. In our business case, products created from API can't be queried via web interface, which is a pain.

cc/ @juliensnz could you please take a look and give us some light pls?


Thanks,

**Comment by Doodoune** [comment] 2018-11-27 13:57
Hi @McSurf84 and @omolto!

What is the version of your PIM? 
Can you provide us some screenshot and/or explanation step by step to reproduce this behavior?

Thanks,
Elodie

**Comment by omolto** [comment] 2018-11-27 14:57
Hi @Doodoune ,

In our case, the version used was

`"akeneo/pim-community-dev": "~2.1.1"`

We haven't checked it on newer versions. The bug is from some time ago.


Regards,

**Comment by Doodoune** [comment] 2019-01-07 15:20
Hi @omolto!

Effectively it's on an old version. But I can't reproduce the error on the newest version (2.3). 
Can you send me some explanation step by step to reproduce this behavior? 

Regards,

**Comment by omolto** [comment] 2019-01-08 09:20
Hi @Doodoune ,

Sorry, we no longer have that version installed and we can not reproduce it now. However, you can try what I explained above.

1. Create a product via API which has a pim_catalog_simpleselect or pim_catalog_multiselect attribute as null
2. Query using API filtering the same attribute as "Is empty". You should get the product created on step 1.
3. Query using WEB filtering the same attribute as "Is empty". We didn't get the product on 2.1.1 version. If it works on 2.3 it means it has been fixed on some release.


Regards,

**Comment by Doodoune** [comment] 2019-02-19 11:05
I close this issue.
This issue is solved in the 2.3 version.

If you still have an issue, feel free to reopen it.

Regards,

**Closed by Doodoune** 2019-02-19 11:05 UTC
