### ISSUE TITLE
Views - Locale is not populated properly while navigating from one view to another view

### ISSUE THREAD

**Issue by karthik32cse** [akeneo/pim-community-dev#9495] opened 2019-01-31 14:49 UTC
**I'm reporting a Bug**

In Views - I have created 2 types of views with 2 different channel, locale and category. When navigating from one view to another view locale is not populated properly.

**Note:** _The same issue present in **Projects** too_

**Version:** 2.3.25

**Comment by Doodoune** [comment] 2019-02-11 16:42
Hi @karthik32cse!

As you can see here: https://help.akeneo.com/pim/v2/articles/manage-your-views.html
View only manage category/category tree, filters and columns. It doesn't depend on locale & channel.
So it's normal that when you switch between views, the locale selector won't change.

But for projects effectively it's not normal. 
For the bug regarding projects, if you are an Enterprise Edition customer, can you please raise this issue to our Support team? (https://akeneo.atlassian.net/servicedesk/customer/portal/8) 

Regards,

**Comment by Doodoune** [comment] 2019-03-21 14:28
I close this issue, it's not a bug for the views.

**Closed by Doodoune** 2019-03-21 14:28 UTC
