### ISSUE TITLE
Enrich => Products page disappears when attribute is created. V 1.5.7 and other

### ISSUE THREAD

**Issue by syrotchukandrew** [akeneo/pim-community-dev#4750] opened 2016-07-20 14:04 UTC
This issue is reproducible on http://demo.akeneo.com/user/login
For version 1.5.7 and other, please go to "Settings > Attributes", create attribute with attribute type 'Reference data simple select' or 'Reference data multi select' and  with flag 'Usable in grid'. After that go to "Enrich > Products" and you can't see products.

**Comment by aRn0D** [comment] 2016-07-20 14:27
Hi syrotchukandrew,

Which is the code and the type of that attribute, please?

Thanks

**Comment by syrotchukandrew** [comment] 2016-07-20 14:56
Hi, 
attribute type: 'Reference data simple select' or 'Reference data multi select';
type: pim_reference_data_multiselect or pim_reference_data_simpleselect
And don't forget useable_as_grid_filter: 1

**Comment by syrotchukandrew** [comment] 2016-07-20 15:00
type: pim_reference_data_simpleselect
code: test_attribute
group: technical
useable_as_grid_filter: 1
available_locales: All
scope: Global


I've just created on http://demo.akeneo.com/#url=/configuration/attribute/56/edit

**Comment by aRn0D** [comment] 2016-07-21 07:51
Hi,

I reproduce it, thanks for raising that issue! it happen because the data validation failed. **Reference data name** is mandatory but you can leave it empty.

**Comment by LaureBro** [comment] 2016-09-20 09:30
Hello @syrotchukandrew, this issue has been fixed on the 1.5.8.
We now display a message saying that the reference data needs a reference data name.
I'm closing this issue.

Best regards, 

Laure

**Closed by LaureBro** 2016-09-20 09:30 UTC
Labels: bug, core-team
