### ISSUE TITLE
Sku In list filter with hyphen

### ISSUE THREAD

**Issue by julienanquetil** [akeneo/pim-community-dev#4630] opened 2016-06-21 10:04 UTC
I try on several version of akeneo and also on the demo one
If you have sku like 123456 and 789654 you can add it to in list filter on the grid view and you got results

but if you have (my case) sku like 123-456 and 789-654 you can add it to the "in list" in the grid view but you didn't have any result.

do you know why ? and how to fix it ?

Thanks

**Comment by LaureBro** [comment] 2016-06-24 08:48
Hello @julienanquetil, 

It's a know bug, it has already been reported here: https://github.com/akeneo/pim-community-dev/issues/4435. We have created a ticket in our bug tracker under the reference PIM-5767.

We'll keep you updated.

Best regards, 

Laure

**Comment by julienanquetil** [comment] 2016-06-24 09:05
Thanks @LaureBro  I didn't see there is already something...
If i have time i will take a look (and try a PR) but not sure to have time in the comming week. 

Thanks

**Comment by Hocdoc** [comment] 2016-06-27 14:24
I also have some issues with String filters with hyphen in our code base.

I think the problem is in `Pim\Bundle\FilterBundle\Filter\ProductValue\StringFilter.php`: 
In `prepareData()` you  escape the String value as a regex:

    $data['value'] = preg_quote($data['value']);

A value like `123-456` will be `123\-456` after escaping. MySQL would then search with `LIKE` for `123\-456`, but doesn't understand this backslash escaping. 

Maybe you should use something like `mysqli_real_escape_string` instead of the `preg_quote` (but I don't know about the Mongo side).

**Comment by julienanquetil** [comment] 2016-07-01 13:12
I know it's not the cleanest one but it's working on my side :

After the 

`$data['value'] = preg_quote($data['value']);;`

I just add :

`$data['value'] = str_replace('\-','-',$data['value']);`

and now I can use the "in list with dash" 

not sure if it will work for every one / config but fit my case :)

**Comment by aRn0D** [comment] 2016-07-05 09:44
@julienanquetil @Hocdoc Perhaps the better should be to fix how OroDatagridBundle create the query. Anyway, every contribution are very welcome. You can send a PR and we will be able to talk about it.

**Comment by Hocdoc** [comment] 2016-07-05 11:00
I don't understand why the String value should get escaped with `preg_quote`?!

> Perhaps the better should be to fix how OroDatagridBundle create the query. 

As far as I can see, the query is always created in `\Pim\Bundle\CatalogBundle\Doctrine\ORM\Filter\StringFilter.php` in `prepareCondition()`. 
We could replace there the SQL `LIKE` with `REGEXP`, but it would be much slower. I think it would be better to escape just quotes instead of all possible regexp characters.

**Comment by julienanquetil** [comment] 2016-07-11 06:33
@aRn0D your fix is very easy.... many thanks

**Comment by LaureBro** [comment] 2016-08-09 09:45
Hello @julienanquetil (and @Hocdoc again), we've fixed this bug in the 1.5 version :) it will be available in the next patch, we're planning to release it this week.

We'll keep you updated.

Best regards,

Laure

**Comment by LaureBro** [comment] 2016-09-01 08:24
Hello, 

This issue has been fixed in the latest PIM version (1.5.8), it's working fine on the 1.6 too.

I'm closing this issue.

Regards,

**Closed by LaureBro** 2016-09-01 08:24 UTC
Labels: bug, core-team, duplicate
