### ISSUE TITLE
Error channel between product grid and product form in views

### ISSUE THREAD

**Issue by alexisfroger** [akeneo/pim-community-dev#3737] opened 2015-12-10 16:47 UTC
When I use a specific view in the product grid and I want update my product, there is a channel error. It isn't the same channel between the product grid and the product form ! In fact, it is the last channel I am using in Akeneo and not my channel view.

For example, I'm in my "Adonix" view with my "Default" channel and I want to update a product.

![image](https://cloud.githubusercontent.com/assets/15442639/11721787/e02c7f28-9f65-11e5-8ce8-7c6e57232de7.png)

If before I used "Wynstor" channel, my channel will be "Wynstor" and not "Default" ! It's dangerous because it will force users to verify the channel  every time !

![image](https://cloud.githubusercontent.com/assets/15442639/11721410/f2f3bc40-9f63-11e5-896c-10a8b19edd30.png)

Is it possible to associate the same channel in the product form and the product grid ?

Thanks

**Comment by LaureBro** [comment] 2015-12-16 15:50
Hello, 

I have tested on our latest version (1.4.13) and the channel selected in the product grid is always the one displayed in the Product Edit Form.
Which version are you using?

Thanks, 
Best regards, 

Laure

**Comment by alexisfroger** [comment] 2016-02-02 08:46
Hi,

I just moved on the 1.4.18 version and there is always the same problem. 

Indeed, the product form save the last channel used. If i change my default channel to a specific channel, next time it will be the specific channel to be used and not my default channel !

Is it possible to configure my default channel for each opening product form it will be used ?

Thanks

**Comment by LaureBro** [comment] 2017-05-11 15:05
Hi @alexisfroger, 

It's a behaviour we would like to keep: if there is no context, we display the default channel in the product edit form. But if you select a specific channel (and if it's not your default channel), you create a context and this context is kept on the product edit form.

It should be possible to override this behaviour with some customisation.

Kind regards, 
Laure

**Comment by pierallard** [comment] 2017-05-23 12:59
Hi @alexisfroger !
I will close this ticket because this issue is the expected behavior of the PIM.
If you want to add extra information about related data of this one, please feel free to re-open it !
Regards

Pierre

**Closed by pierallard** 2017-05-23 12:59 UTC
Labels: feature-request, question
