### ISSUE TITLE
Not visible attribute fields in bulk editing product values

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#9455] opened 2019-01-29 21:54 UTC
**I'm reporting a Bug**
2.3

http://demo.akeneo.com/#/enrich/product/
1. Select few products.
2. Click on Bulk Action.
3. Click on Edit attributes values.
4. Select several attributes. For example Price, Name, Description.

Only fields of the first group are visible. How to edit fields from other groups?
The same problem when choosing fields when setting up export of products.

![mass_action](https://user-images.githubusercontent.com/2612186/51943541-c42caf80-242a-11e9-84ee-44e33bb32b90.jpg)

**Comment by Doodoune** [comment] 2019-04-03 10:50
Hi!
It's not a bug it's a "work as design".

As you can see in your second screenshot the filter on attribute group is automatically selected to "ERP".
So you will see only attributes of the group "ERP". 

You can select another filter like "all attributes groups" to see all your attributes.
Regards,

**Comment by userz58** [comment] 2019-04-03 12:05
You are right, but how should I have known about this that by default only the group of the last selected attribute is displayed?
It seems to me that it is necessary to change the behavior of the filter and display all the selected attributes.

**Comment by Doodoune** [comment] 2019-05-14 15:37
Hi @userz58!

We fix this issue in the 2.3.43 version! :tada: 
Please upgrade your PIM.

I close this issue, feel free to reopen it if needed.

Regards,

**Closed by Doodoune** 2019-05-14 15:37 UTC
