### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by Nebojsaa** [akeneo/pim-community-dev#6721] opened 2017-09-11 13:00 UTC
This is our System info. I can't see why is it interesting. [akeneo-pim-system-info_2017-09-11_14-49.txt](https://github.com/akeneo/pim-community-dev/files/1292566/akeneo-pim-system-info_2017-09-11_14-49.txt)

And every time I try to install it it gives to me this awful error. 
See the picture below.
![screenshot from 2017-09-11 14-52-32](https://user-images.githubusercontent.com/3692864/30275344-52483a68-9701-11e7-9d03-4274d18f274f.png)

There isn't anything in the apache nor symfony log. 
Expected behavior is that I have installation of Akeneo. 

Already tried: giving all the rights (rwx) to this user, trying to reinstall assets (followed their documentation), removed cache (couple of thousand of times)

If you need more info about this, let me know. 

Does anyone have had issues like we do ?

**Comment by solivier** [comment] 2017-09-11 13:29
Hi @Nebojsaa, 

Thanks for reporting this weird behavior, but I cannot reproduce it on my side :/ 
What info do you have in the browser console ? Btw it seems you are using a mysql version < 5.1 and we recommend to use a version in between >= 5.1 and <= 5.6 

Cheers,
Olivier.

**Comment by Nebojsaa** [comment] 2017-09-11 14:03
Hmmm, that's odd. Because I am sure that I have on mysql server this info. 
![screenshot from 2017-09-11 15-51-46](https://user-images.githubusercontent.com/3692864/30277799-2587119a-9709-11e7-84c2-7f5ec59fc732.png)
But nevertheless I believe that we have discovered where the problem lies. It's about the routes. 
Look at this link. 
![screenshot from 2017-09-11 15-53-06](https://user-images.githubusercontent.com/3692864/30277859-56010948-9709-11e7-9b94-def954fc1294.png)

But then when I login I get this. 
![screenshot from 2017-09-11 15-53-52](https://user-images.githubusercontent.com/3692864/30277899-6f3761e6-9709-11e7-8bc8-57238506cda6.png)

Also look at this from the browser console from the first page: 
![screenshot from 2017-09-11 16-02-00](https://user-images.githubusercontent.com/3692864/30278416-96f2cc1a-970a-11e7-8b09-1d0097435fbd.png)

And this is from the second page: 
![screenshot from 2017-09-11 16-03-03](https://user-images.githubusercontent.com/3692864/30278480-ba20b742-970a-11e7-9ff8-2ac020e542ba.png)

**Comment by solivier** [comment] 2017-09-11 14:12
hum weird it seems you have a problem with your assets. Can you try this command ? 

> rm -Rf ./var/cache/* ./web/bundles/* ./web/css/* ./web/js/*;app/console pim:install:ass -e=prod;app/console assets:install --symlink web --env=prod

**Comment by Nebojsaa** [comment] 2017-09-12 06:18
Have tried that couple of thousand of times. 
I have read through most of Akeneo's documentation and have seen that already. 
Do you have any other ideas ?

**Comment by solivier** [comment] 2017-09-12 13:37
@Nebojsaa I guess it's more a problem with the apache configuration. The web folded should be at the root of your configuration.
Something like this:

> 
> DocumentRoot /path/to/pim/root/web/
>     <Directory /path/to/pim/root/web/>

Here it seems not to be like this. Could you provide your apache configuration ?

**Comment by Doodoune** [comment] 2018-11-16 14:35
Hi @Nebojsaa!

After one year without feedback, allow me to close this issue.
Feel free to re-open it if you still have this issue.

Regards,
Elodie

**Closed by Doodoune** 2018-11-16 14:35 UTC
Labels: Waiting for feedback, question, to reproduce
