### ISSUE TITLE
2.1.4 : Cannot remove variant axis of a product

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#7741] opened 2018-02-27 14:50 UTC
If I import a product with a variant axis, it gets imported. But when I want to change the product from a product model-like product to a regular product and remove the variant axis I get the message `Variant axis "name_of_variant_axis" cannot be modified, "" given`.

For example, import 1 has the following dataset:

sku|family|parent|name_of_variant_axis
--- | ----- | ----- | -------------------
|abc|default|some_parent|some_value|
|def|default|some_parent|some_other_value|

import 2:

sku|family|parent|name_of_variant_axis
--- | ----- | ----- | -------------------
|abc|default|some_parent|some_value|
|def|default| | |

What I expect with the second import is that the product will no longer be a variant_product, but just a simple 'normal' product. However I get the error of the variant axis (Thrown by the validator), even though the import states that I no longer have a parent, so the validation should not even be required.

**Comment by thatside-zaraffa** [comment] 2018-03-12 16:02
Also I've noticed that it is not possible to remove family variants from family page.

**Comment by damien-carcel** [comment] 2018-03-20 16:01
Hello @kanduvisla and @thatside-zaraffa .

It is indeed a wanted behavior for now. Changing a variant axis or removing family variants have huge impacts on variant products and product models.
We just didn't have the time to handle it correctly for the 2.0 when we introduced the new product modelization. So preventing those modifications was the quickest way to ensure a user cannot break its data.

Removing the family variants will be available this week in the new 2.2 version. It was a feature a lot of people asked for.
However, regarding the modification of the variant axes, it is not something so much people ask for. It will probably be available one day, but I cannot provide you any ETA (certainly not in 2.3, cannot say if it will be in 3.x nor in which minor version).

Kind regards,
Damien.

**Comment by thatside-zaraffa** [comment] 2018-03-21 07:53
Hello @damien-carcel .
The problem is that it is possible to try to delete a family which has variants - but the error message does not provide any information (actually it is empty).

**Comment by damien-carcel** [comment] 2018-03-21 08:03
Hello @thatside-zaraffa .

This has been fixed too in 2.2 => https://github.com/akeneo/pim-community-dev/pull/7791.
It was indeed not a very user friendly behavior.

Regards,
Damien

**Closed** 2018-03-29 11:52 UTC
Labels: question
